### ISSUE TITLE
The example thief for the steal skill does not function properly.

### ISSUE THREAD

**Issue by Jwguy0** [BerndiVader/mmCustomSkills26#35]
I've installed the plugin for customskills and I imported the example thief with the steal skill to test it out.

The thief just runs at players but never steals or does anything else.

**Comment by muhahahahe** [comment]
i guess it was sorted out in the discord, if not:

Thief:
  Type: villager
  Health: 20
  Damage: 0
  Modules:
    ThreatTable: true
  Options:
    AlwaysShowName: false
    Despawn: true
  AIGoalSelectors:
    - 0 clear
    - 1 meleeattack
    - 2 avoidskeletons
    - 3 avoidzombies
    - 4 randomstroll
    - 5 float
  AITargetSelectors:
    - 0 clear
    - 1 players
  Skills:
    - setstance{stance=gostealing} @self ~onSpawn 1
    - skill{s=FleeGotSomeStuff;sync=true} ~onSignal:steal_ok 1
    - skill{s=FleeButGotNothing;sync=true} ~onSignal:steal_fail 1
    - skill{s=Steal} @nearestplayer ~onTimer:60 1
    - DropStolenItems ~onDeath 1

Steal:
  Cooldown: 1
  Conditions:
    - stance{s=gostealing} true
  TargetConditions:
    - distance{d=<3} true
    - lineofsight
  Skills:
    - steal{items=DIAMOND_SWORD:1,IRON_SWORD:1,DIAMOND:3,EMERALD:3;failsignal=steal_fail;oksignal=steal_ok} 0.75
  
FleeGotSomeStuff:
  Cooldown: 1
  Skills:
    - setstance{stance=flee} @self
    - RunAIGoalSelector{s=clear}
    - delay 2
    - RunAIGoalSelector{s=fleeplayers}
    - effect:smoke @self
    - potion{type=SPEED;duration=200;level=1} @self
    - delay 400
    - effect:smoke @self
    - remove @self
  
FleeButGotNothing:
  Cooldown: 1
  Skills:
    - setstance{stance=flee} @self
    - RunAIGoalSelector{s=clear}
    - delay 2
    - RunAIGoalSelector{s=randomstroll}
    - delay 400
    - effect:smoke @self
    - remove @self
