### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by SkyPremium** [BerndiVader/mmCustomSkills26#63]
Hello, please add one new condition for the plugin MythicMobsExtension

- leir{isb=[BOOLEAN];types=TheSkeletonKing,Another7331Mob;amount=[RANGEDVALUE];radius=[VALUE];npc=[BOOLEAN];action=[boolean]}
To be able to use the mobs from MythicMobs

**Comment by BerndiVader** [comment]
Hi! There already is a condition called mir / mythicmobsinradius. But thank you for your suggestion.

**Comment by SkyPremium** [comment]
I cannot find this condition in the documentation
