### ISSUE TITLE
Objective name doesn't allow placeholders.

### ISSUE THREAD

**Issue by ItsJabba** [BerndiVader/mmCustomSkills26#77]
I use command panels for GUI of my server and when I want to display progress, before, I was able to show the quest objective which without mythic mobs would show the progress by doing `%quests_player_current_objectives_<quest>%` this displays the objective of the quest, it works for the addon aside from you are not able to see the values of your progress. I tried to use %c% and %s% but these didn't work and just display '%c%' and '%s%' rather than the values. 
```
'1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 15
              data:
                Objective Name: Kill Cave Spiders %c%:%s%
                Conditions: NONE
                TargetConditions: NONE
                Internal Mobnames: CaveSpider
                Mob Level: '0'
                Mob Faction: ANY
                Notifier enabled: false
                Notifier msg: ''
```
I tried to use the notifier msg but that just wasn't what I was looking for, though it did display %c% and %s% properly. I do not usually use GitHub as I just created an account to contact you, so if you reply to this please send a message to Jabba#8769 on discord. If you don't want to message me on discord, please still respond here at the least.

Thank you very much, and sorry for the inconvenience this may bring,
-Jake / Jabba#8769

**Comment by BerndiVader** [comment]
This issue belongs to https://github.com/BerndiVader/MythicMobsQuestsModule

Hello Jabba!

You can achieve this by adding %count% to your objective name. The %s% and %c% placeholders are for internal objective use only, to customize the notifier message. 

When i take the quest below and use the /papi parse command for the mentioned placeholder, i receive `just add 0/5 for a counter` 

```  custom1:
    name: simplequest
    ask-message: kill some mythicmobs
    finish-message: well done!
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: Kill MythicMobs Objective
              count: 5
              data:
                Objective Name: just add %count% for a counter
                Conditions: NONE
                TargetConditions: NONE
                Internal Mobnames: ANY
                Mob Level: '0'
                Mob Faction: ANY
                Notifier enabled: true
                Notifier msg: 'Killed %c% out of %s%'
    options:
      allow-commands: true
      allow-quitting: true
      use-dungeonsxl-plugin: false
      use-parties-plugin: true
      share-progress-level: 1
      require-same-quest: true
```
