### ISSUE TITLE
Incompatibility with Purpur (Paper fork)

### ISSUE THREAD

**Issue by Keeg-Turner** [BerndiVader/mmCustomSkills26#88]
**Summary**

Upon loading the plugin on a Purpur server, it spits an error that does not arise on Paper.

**Steps to reproduce**

1. Download Purpur here: https://ci.pl3x.net/job/Purpur/
2. Boot the Purpur server with MythicMobs and MythicMobsExtension in the plugins folder.
3. Observe the above error message.

**Current behavior**

Nothing bad happens after this when the server is idle, but I am concerned about the impact it may have on certain mob packs.

**Intended correct behavior**

I would expect there to be no compatility issue and, by extension, no error message.

**Server log file**

https://pastebin.com/AgJYxiLp

**Debug log snippet**

The bugged behaviour occurs in the above startup log from lines 731 to 746.

**Proposed fixes**

I asked the folks in the Purpur community about this and they helpfully directed me towards a bug (and its respective fix) that was recently found in another plugin and appears to be caused by the same type of issue: https://github.com/elBukkit/MagicPlugin/issues/816

**Comment by LW-MrWU** [comment]
https://github.com/elBukkit/MagicPlugin/issues/816
the "MagicPlugin" had the same problem.
it's a simple fix.

**Comment by BerndiVader** [comment]
Hi! Updated nathans compatiblitylib. It should work now.

**Comment by Keeg-Turner** [comment]
Hey! Yes, this issue appears to be fixed in build 412, however now I'm getting some console spam in the form of a different error message every few seconds; I'll open a new issue for this. Thanks for the help 😄
Edit: Actually, it seems somebody has beaten me to it; I'm experiencing this same issue: https://github.com/BerndiVader/MythicMobsExtension/issues/89
